# This workflow builds and unit tests both main C++ API and also build/data tools for metadata generation.

name: Testing C++ API
on: pull_request
permissions:
  contents: read

jobs:
  cpp-test:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    
    - name: Set up C++ environment
      run: |
        sudo apt-get update && \
        sudo apt-get install -y --fix-missing libboost-all-dev \
        cmake cmake-curses-gui libprotobuf-dev libgtest-dev libre2-dev \
        libicu-dev libboost-dev libboost-thread-dev libboost-system-dev \
        protobuf-compiler
      
    - name: Build C++
      run: |
        cd cpp
        mkdir build
        cd build
        cmake ..
        make
    
    - name: Test C++ Build Tools
      run: |
        ./cpp/build/tools/generate_geocoding_data_test
    
    - name: Test C++ API
      run: |
        ./cpp/build/libphonenumber_test
